name: build-and-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup ROS 2 Foxy
      run: |
        sudo apt-get update && sudo apt-get install -y curl gnupg2 lsb-release
        curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y ros-foxy-desktop

    - name: Install rsync and other dependencies
      run: |
        sudo apt-get install -y rsync python3-colcon-common-extensions

    - name: Build workspace
      run: |
        source /opt/ros/foxy/setup.bash
        colcon build

    - name: Run tests
      run: |
        source install/setup.bash
        colcon test
        colcon test-result --verbose

