name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment variables
        run: |
          echo "export ROS2_BATTERY_INFO_SKIP=true" >> $GITHUB_ENV
      - name: build and test
        run: |
          rsync -av ./ /root/ros2_ws/src/mypkg/
          cd /root/ros2_ws
          bash -xv ./src/mypkg/test/test.bash /root

