name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04
    container: ryuichiueda/ubuntu22.04-ros2:latest

    steps:
      - uses: actions/checkout@v2

      - name: Install rsync and ROS 2 Foxy
        run: |
          apt-get update
          apt-get install -y rsync python3-vcstool

          sudo apt update
          sudo apt install -y locales lsb-release curl gnupg2
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key --keyring /usr/share/keyrings/ros-archive-keyring.gpg add -
          sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] https://packages.ros.org/ros2/ubuntu $(lsb_release -c | awk '{print $2}') main" > /etc/apt/sources.list.d/ros2.list'
          sudo apt update
          sudo apt install -y ros-foxy-desktop

      - name: Build and test
        run: |
          source /opt/ros/foxy/setup.bash
          rsync -av ./ /root/ros2_jyuuden_ws/src/mypkg/ 
          cd /root/ros2_jyuuden_ws
          colcon build --symlink-install
          . install/setup.bash
          bash -xv ./src/mypkg/test/test.bash /root

