name: Test ROS 2 Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    container: ros:foxy

    steps:
      - uses: actions/checkout@v2

      - name: Install necessary packages
        run: |
          apt-get update
          apt-get install -y curl gnupg2 rsync python3-colcon-common-extensions

      - name: Set up workspace and test
        run: |
          bash -c "
            mkdir -p /root/ros2_jyuuden_ws/src/mypkg
            rsync -av ./ /root/ros2_jyuuden_ws/src/mypkg/
            dir=/root
            [ \"\$1\" != \"\" ] && dir=\"\$1\"
            cd \$dir/ros2_jyuuden_ws || { echo \"Workspace not found\"; exit 1; }
            colcon build --symlink-install || { echo \"Build failed\"; exit 1; }
            source install/setup.bash
            ros2 run mypkg batterytalker &
            TALKER_PID=\$!
            ros2 topic echo /battery_status > /tmp/battery_status.log &
            ECHO_PID=\$!
            trap \"kill -SIGINT \$TALKER_PID \$ECHO_PID; exit\" SIGINT SIGTERM
            tail -f /tmp/battery_status.log
          "

