name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04
    container: ros:foxy

    steps:
      - uses: actions/checkout@v2

      - name: Install rsync
        run: |
          apt-get update
          apt-get install -y rsync

      - name: Build and test
        run: |
          rsync -av ./ /root/ros2_jyuuden_ws/src/mypkg/
          cd /root/ros2_jyuuden_ws
          bash -xv ./src/mypkg/test/test.bash /root

