name: ROS 2 Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ROS 2 environment
        run: |
          sudo apt update
          sudo apt install -y curl gnupg2 lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos -o ros2.repos
          vcs import src < ros2.repos
          sudo apt update
          sudo apt install -y python3-colcon-common-extensions python3-pip

      - name: Build workspace
        run: |
          source /opt/ros/foxy/setup.bash
          colcon build --symlink-install
         
      - name: Run tests
        run: |
          source install/setup.bash
          ros2 run mypkg batterytalker &
          sleep 5
          if ros2 topic echo /battery_status --once > /tmp/battery_status.log; then
            echo "Test passed: Battery status published successfully."
          else
            echo "Test failed: Battery status not published."
            exit 1
          fi

