name: build-and-test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup ROS 2 (Humble)
      run: |
        sudo apt-get update && sudo apt-get install -y curl gnupg2 lsb-release
        curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y ros-humble-desktop

    - name: Install dependencies
      run: |
        sudo apt-get install -y python3-colcon-common-extensions
        python3 -m pip install --upgrade pip
        python3 -m pip install pytest
        echo "export PATH=$PATH:/root/.local/bin" >> ~/.bashrc
        source ~/.bashrc
        which pytest

    - name: Build workspace
      run: |
        source /opt/ros/humble/setup.bash
        colcon build

    - name: Run tests (excluding flake8 and copyright tests)
      run: |
        source install/setup.bash
        pytest --deselect mypkg.test.test_flake8::test_flake8 --deselect mypkg.test.test_copyright::test_copyright
        pytest --maxfail=5 --disable-warnings

