name: Test BatteryTalker Node

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    container: ros:foxy-ros-base

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-psutil rsync
          sudo apt-get install -y ros-foxy-rclpy ros-foxy-std-msgs

      - name: Setup ROS 2 environment
        run: |
          bash -c "source /opt/ros/foxy/setup.bash"

      - name: Prepare directories and sync files
        run: |
          mkdir -p /root/ros2_jyuuden_ws/src/mypkg
          rsync -av ./ /root/ros2_jyuuden_ws/src/mypkg/

      - name: Build workspace
        run: |
          cd /root/ros2_jyuuden_ws
          colcon build --symlink-install

      - name: Run BatteryTalker Node
        run: |
          source /root/ros2_jyuuden_ws/install/setup.bash
          python3 ./src/mypkg/test/batterytalker.py

