name: test
on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    container: ryuichiueda/ubuntu22.04-ros2:latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: |
          mkdir -p /root/ros2_jyuuden_ws/src/mypkg
          rsync -av ./ /root/ros2_jyuuden_ws/src/mypkg/
          cd /root/ros2_jyuuden_ws
          bash -c 'source /opt/ros/humble/setup.bash && colcon build && source install/setup.bash && timeout 10 bash -e -xv ./src/mypkg/test/test.bash /root'

