name: Test ROS 2 Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    container: ryuichiueda/ubuntu22.04-ros2:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ROS 2 environment
        run: |
          . /opt/ros/foxy/setup.bash

      - name: Sync code to workspace
        run: |
          mkdir -p /root/ros2_jyuuden_ws/src
          
          rsync -avR ./ /root/ros2_jyuuden_ws/src/

      - name: Build ROS 2 workspace
        run: |
          cd /root/ros2_jyuuden_ws
          colcon build --symlink-install

      - name: Source ROS 2 workspace
        run: |
          . /root/ros2_jyuuden_ws/install/setup.bash

      - name: Run tests
        run: |
          bash -xv /root/ros2_jyuuden_ws/src/mypkg/test/test.bash

