name: test
on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    container: ryuichiueda/ubuntu22.04-ros2:latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: |
          rsync -av ./ /root/ros2_jyuuden_ws/src/mypkg/
          cd /root/ros2_jyuuden_ws
          colcon build
          source install/setup.bash
          bash -xv ./src/mypkg/test/test.bash /root
