name: test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    container: ros:foxy
    steps:
      - name: Set up workspace and test
        run: |
          mkdir -p /root/ros2_jyuuden_ws/src/mypkg

          dir=/root
          [ "$1" != "" ] && dir="$1"
          cd $dir/ros2_jyuuden_ws || { echo "Workspace not found"; exit 1; }
          colcon build --symlink-install || { echo "Build failed"; exit 1; }
          source install/setup.bash
          ros2 run mypkg batterytalker &
          TALKER_PID=$!
          ros2 topic echo /battery_status > /tmp/battery_status.log &
          ECHO_PID=$!
          trap "kill -SIGINT $TALKER_PID $ECHO_PID; exit" SIGINT SIGTERM
          tail -f /tmp/battery_status.log
