name: test
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    container: ros:foxy
    steps:
      - uses: actions/checkout@v2
      - name: build and test
        run: |
          cd /root/ros2_jyuuden_ws
          bash -xv ./src/mypkg/test/test.bash /root
